/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.hw01;

import org.apache.commons.cli.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Options options = new Options();

        Option batch = Option.builder("b").longOpt("batch").argName("file").hasArg().desc("batch file containing expressions to evaluate").build();
        Option output = Option.builder("o").longOpt("output").argName("file").hasArg().desc("output file").build();
        Option help = Option.builder("h").longOpt("help").desc("print usage message").build();

        options.addOption(batch);
        options.addOption(help);
        options.addOption(output);

        CommandLineParser parser = new DefaultParser();
        try {
            // parse the command line arguments
            CommandLine line = parser.parse(options, args);

            if (line.hasOption("help")) {
                HelpFormatter formatter = new HelpFormatter();
                formatter.printHelp("eval [OPTIONS]", "Evaluation of simple mathematical expressions\n\n", options, "\nCopyright (C) 2021 Isaac D. Griffith");
                System.exit(0);
            }

            if (line.hasOption("batch")) {
                System.out.println("Batch value: " + line.getOptionValue("batch"));
            }

            if (line.hasOption("output")) {
                System.out.println("Output value: " + line.getOptionValue("output"));
            }
        } catch(ParseException exp) {
            System.err.println("Parsing failed. Reason: " + exp.getMessage());
        }
    }
}


